= Tulip: Load Testing, Stress Testing and Performance Regression Testing
v2.0.0
:toc: left
:sectnums:
:source-highlighter: highlightjs
:stylesdir: css
:stylesheet: adoc-foundation.css

image::tulip_logo.svg[width=128]

== Introduction

https://github.com/wfouche/Tulip[Tulip] is an advanced open-source software tool designed for load testing, stress testing and performance regression testing. It serves as a robust solution for evaluating the performance and stability of web applications under varying conditions, ensuring they can handle high traffic and stress levels efficiently. Similar to well-known tools like JMeter, Gatling and Locust, Tulip provides powerful capabilities to simulate real-world scenarios and generate comprehensive reports, helping developers identify and resolve potential bottlenecks.

<Under construction.>

//
// https://www.freepik.com/free-vector/tulip-flower-logo-gradient-colorful_41061958.htm
//
// logo designed by *Freepik*
//
// https://support.freepik.com/s/article/Attribution-How-when-and-where
//

== Maven Central

Tulip is now available on Maven Central at:

* https://central.sonatype.com/namespace/io.github.wfouche.tulip

=== Maven (xml)

[source,xml]
----
<dependency>
    <groupId>io.github.wfouche.tulip</groupId>
    <artifactId>tulip-runtime</artifactId>
    <version>2.0.0</version>
</dependency>
----

=== Gradle (groovy)

[source,groovy]
----
implementation 'io.github.wfouche.tulip:tulip-runtime:2.0.0'
----

=== Gradle (kts)

[source,kotlin]
----
implementation("io.github.wfouche.tulip:tulip-runtime:2.0.0")
----

== Tulip Releases

* [v2.0.0] - 2024/12/01

** https://github.com/wfouche/Tulip/releases?q=v2.0.0&expanded=true

== License

[source,text]
----
Copyright 2024 Werner Fouché

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
----

// Links

// https://github.com/errata-ai/vale

// https://redhat-documentation.github.io/vale-at-red-hat/docs/main/user-guide/asciidoc-style-for-vale/
